% Connectivity_Video.m
% Requires sim_data.mat generated by TEST5.m
%
% Generates two MP4 videos:
%   1. connectivity_threshold_sweep.mp4
%      — Static connectivity graph as Pr_threshold increases from weak to strong.
%        Links disappear as the threshold tightens. Shows how network
%        degrades from fully connected to isolated nodes.
%
%   2. connectivity_timevarying.mp4
%      — Time-varying graph using the P(out) model at a fixed threshold.
%        Links randomly flicker on/off based on their outage probability.
%        Shows dynamic network topology over time.

clc; clear; close all;
load('sim_data.mat');   % loads: ss, n, Locations, distMatrix, freq, rxSens, Pr_threshold

lat = Locations(:,1);
lon = Locations(:,2);

% Axis limits with padding for consistent framing
lonPad = 0.001; latPad = 0.001;
xLim   = [min(lon)-lonPad, max(lon)+lonPad];
yLim   = [min(lat)-latPad, max(lat)+latPad];


%% =========================================================
%  VIDEO 1: Connectivity Graph as Threshold Sweeps
%
%  At each frame, threshold increases from rxSens (-100 dBm)
%  to a tight threshold (-40 dBm). Links that fall below the
%  current threshold are dropped — watch the network thin out.
% =========================================================

threshold_sweep = linspace(rxSens, -40, 60);   % 60 frames

v1 = VideoWriter('connectivity_threshold_sweep.mp4', 'MPEG-4');
v1.FrameRate = 8;     % 8 fps — slow enough to follow link drops
v1.Quality   = 90;
open(v1);

fig1 = figure('Position', [100 100 800 650], 'Color', 'w');

for f = 1:length(threshold_sweep)
    thr = threshold_sweep(f);

    % Binary connectivity at this threshold
    Connectivity = ss >= thr;
    Connectivity(logical(eye(n))) = 0;

    nActiveLinks = sum(sum(triu(Connectivity, 1)));

    clf(fig1);
    ax = axes('Parent', fig1);
    hold(ax, 'on'); grid(ax, 'on');

    % Color links by signal strength relative to current threshold
    for i = 1:n
        for j = i+1:n
            if Connectivity(i,j)
                avgPwr  = (ss(i,j) + ss(j,i)) / 2;
                margin  = avgPwr - thr;   % dB above threshold

                % Green = strong margin, yellow = near threshold
                linkColor = [1 - min(margin/30, 1), ...
                             min(margin/20, 1), ...
                             0.1];
                plot(ax, [lon(i) lon(j)], [lat(i) lat(j)], ...
                     'Color', linkColor, 'LineWidth', 1.5);
            end
        end
    end

    % Nodes
    scatter(ax, lon, lat, 60, 'filled', ...
            'MarkerFaceColor', [0.15 0.35 0.75], ...
            'MarkerEdgeColor', 'k', 'LineWidth', 0.8)

    % Node labels
    for i = 1:n
        text(ax, lon(i)+0.00005, lat(i)+0.00005, sprintf('%d', i), ...
             'FontSize', 7, 'Color', [0.2 0.2 0.2])
    end

    xlim(ax, xLim); ylim(ax, yLim);
    xlabel(ax, 'Longitude', 'FontSize', 11)
    ylabel(ax, 'Latitude',  'FontSize', 11)
    title(ax, sprintf('Connectivity Graph  |  Threshold = %.1f dBm  |  Active Links = %d', ...
                      thr, nActiveLinks), 'FontSize', 12)

    % Color legend annotation
    annotation(fig1, 'textbox', [0.15 0.01 0.7 0.04], ...
               'String', 'Link color: Green = strong margin above threshold   |   Yellow = near threshold', ...
               'EdgeColor', 'none', 'FontSize', 8, 'HorizontalAlignment', 'center');

    hold(ax, 'off');
    drawnow;

    frame = getframe(fig1);
    writeVideo(v1, frame);
end

close(v1);
fprintf('Saved: connectivity_threshold_sweep.mp4\n');


%% =========================================================
%  VIDEO 2: Time-Varying Graph using P(out) Model
%
%  Recompute sigmoid P(out) from ss, then at each frame
%  randomly realize the graph: link (i,j) is up with prob
%  1 - P(out | ss(i,j)).
% =========================================================

% Sigmoid steepness (use fitted value if available, else default)
k_fit = 0.3;
if exist('sim_data.mat', 'file')
    saved = load('sim_data.mat');
    if isfield(saved, 'k_fit')
        k_fit = saved.k_fit;
    end
end

Pout_matrix = 1 ./ (1 + exp(k_fit * (ss - Pr_threshold)));
Pout_matrix(logical(eye(n))) = 1;
Pconnect    = 1 - Pout_matrix;

nFrames = 60;   % 60 time steps

v2 = VideoWriter('connectivity_timevarying.mp4', 'MPEG-4');
v2.FrameRate = 6;
v2.Quality   = 90;
open(v2);

fig2 = figure('Position', [100 100 800 650], 'Color', 'w');

activeLinkHistory = zeros(1, nFrames);

for f = 1:nFrames
    % Probabilistic link realization
    randMat     = rand(n, n);
    ActiveLinks = (randMat < Pconnect) & ~eye(n, 'logical');
    ActiveLinks = triu(ActiveLinks, 1);
    ActiveLinks = ActiveLinks | ActiveLinks';

    activeLinkHistory(f) = sum(sum(triu(ActiveLinks, 1)));

    clf(fig2);
    ax = axes('Parent', fig2);
    hold(ax, 'on'); grid(ax, 'on');

    % Draw active links
    for i = 1:n
        for j = i+1:n
            if ActiveLinks(i,j)
                plot(ax, [lon(i) lon(j)], [lat(i) lat(j)], ...
                     'Color', [0.15 0.65 0.25], 'LineWidth', 1.4);
            end
        end
    end

    % Draw inactive links faintly for reference
    for i = 1:n
        for j = i+1:n
            if ~ActiveLinks(i,j)
                plot(ax, [lon(i) lon(j)], [lat(i) lat(j)], ...
                     'Color', [0.85 0.85 0.85], 'LineWidth', 0.5);
            end
        end
    end

    % Nodes — color by how many active links they currently have
    nodeDegree = sum(ActiveLinks, 2);
    scatter(ax, lon, lat, 70, nodeDegree, 'filled', ...
            'MarkerEdgeColor', 'k', 'LineWidth', 0.8)
    colormap(ax, 'hot'); colorbar(ax);
    clim(ax, [0 n-1]);

    for i = 1:n
        text(ax, lon(i)+0.00005, lat(i)+0.00005, sprintf('%d', i), ...
             'FontSize', 7, 'Color', [0.1 0.1 0.1])
    end

    xlim(ax, xLim); ylim(ax, yLim);
    xlabel(ax, 'Longitude', 'FontSize', 11)
    ylabel(ax, 'Latitude',  'FontSize', 11)
    title(ax, sprintf('Time-Varying Graph  |  t = %d  |  Active Links = %d / %d', ...
                      f, activeLinkHistory(f), n*(n-1)/2), 'FontSize', 12)
    cb = colorbar(ax);
    cb.Label.String = 'Node Degree (active links)';

    hold(ax, 'off');
    drawnow;

    frame = getframe(fig2);
    writeVideo(v2, frame);
end

close(v2);
fprintf('Saved: connectivity_timevarying.mp4\n');

%% Summary stats
fprintf('\n--- Time-Varying Graph Summary ---\n')
fprintf('Mean active links per frame : %.1f / %d\n', mean(activeLinkHistory), n*(n-1)/2)
fprintf('Min active links            : %d\n', min(activeLinkHistory))
fprintf('Max active links            : %d\n', max(activeLinkHistory))
fprintf('Std dev                     : %.2f\n', std(activeLinkHistory))
